FEATURE_TEMPLATES = {
    "obj_distance_decrease": [
        "Move closer to {obj}",
        "Stay close to {obj}",
        "Decrease distance to {obj}",
        "Keep a smaller distance from {obj}",
    ],
    "obj_distance_increase": [
        "Move further away from {obj}",
        "Stay away from {obj}",
        "Increase distance to {obj}",
        "Keep a bigger distance from {obj}",
        "Avoid {obj}",
    ],
    "z_cart_decrease": [
        "Move lower",
        "Move down",
        "Stay down",
        "Go to the bottom",
        "Down",
        "Low",
    ],
    "z_cart_increase": [
        "Move higher",
        "Move up",
        "Stay up",
        "Stay on the upper part",
        "Up",
        "Top",
        "Go to the top",
    ],
    "x_cart_decrease": [
        "Stay on the left",
        "Go to the left",
        "Move left",
        "Move more towards the left",
        "Left",
    ],
    "x_cart_increase": [
        "Stay on the right",
        "Go to the right",
        "Move right",
        "Move more towards the right",
        "Right",
    ],
    "y_cart_decrease": [
        "Stay at the back",
        "Go to the back",
        "Move back",
        "Stay back",
        "Move backward",
        "Go behind",
    ],
    "y_cart_increase": [
        "Stay at the front",
        "Go to the front",
        "Move front",
        "Stay front",
        "Move forward",
    ],
}
